name: Apply - Terraform
on: workflow_dispatch
jobs:
    apply:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
        - run: ls -l

#        - run: make dev-apply vault_token=$(vault_token)
#          env:
#            vault_token: ${{ secrets.VAULT_TOKEN }}  #We need to add terraform code in runner
